### ISSUE TITLE
Problem with training custom dataset

### ISSUE THREAD

**Issue by pentadotddot** [shivamswarnkar/Image-Generator#1]
Hi!

I am trying to run your code on my custom dataset (images has various sizes but mostly 512x512), and I get this error:
`python train.py --dataroot ./data/NFT --num_epochs 25
Starting Training Loop....
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    train_gan(args)
  File "/home/mobilrouter/NFT_project/GAN/Image-Generator/DCGAN/train.py", line 94, in train_gan
    errD_real = criterion(real_outputD, labels)
  File "/home/mobilrouter/.conda/envs/Mobil_Torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mobilrouter/.conda/envs/Mobil_Torch/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 530, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/mobilrouter/.conda/envs/Mobil_Torch/lib/python3.8/site-packages/torch/nn/functional.py", line 2525, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(
RuntimeError: Found dtype Long but expected Float
`

Pls give me some hints:)

**Comment by shivamswarnkar** [comment]
Hey @pentadotddot ! What's your Pytorch version?

**Comment by shivamswarnkar** [comment]
I think you're using latest torch version, so this should fix it for you 55b6d066c84c615403e48c27e77ee017cf260955

Thanks for pointing this out. I'll close the issue now, you can reopen it if your issue still persists.
